######################################################################
# Automatically generated by qmake (2.01a) Mon Aug 27 15:02:08 2012
######################################################################

TEMPLATE = app
TARGET = peerster
DEPENDPATH += .
INCLUDEPATH += .
QT += widgets network

# Input
HEADERS += main.hh \
    netsocket.h \
    peer.h \
    node.h
SOURCES += main.cc \
    netsocket.cpp \
    peer.cpp \
    node.cpp
